### ISSUE TITLE
medspacy QuickUMLS syntax

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#107]
With the version of MedSpacy prior to support of the SpaCy 3 use of pipe names to add pipes, I used the following syntax to add a QuickUMLS pipe with explicit parameters:

`quickumls_component = SpacyQuickUMLS(nlp, 'C:/QuickUMLS', threshold=0.95)`
`nlp.add_pipe(quickumls_component, after="target_matcher")`

After refreshing my MedSpaCy download with the version supporting SpaCy 3, I expected the following syntax to work:

` nlp.add_pipe('medspacy_quickumls', after="medspacy_target_matcher", config={'quickumls_path':'C:/QuickUMLS', 'threshold':0.95})`

but I get the following error:

> Config validation error
> 
> medspacy_quickumls -> threshold   extra fields not permitted

I find having the ability to set the threshold parameter important for getting QuickUMLS to perform optimally with my data, and the _quickumls.py create_quickumls(nlp, name="medspacy_quickumls", quickumls_path=None) method has no way to pass a threshhold parameter to SpacyQuickUMLS.

It seems like it would be a minor and useful enhancement to enable medspacy_quickumls pass all of the possible additional arguments to SpacyQuickUMLS.  For example, the best_match argument could prove useful to me at some point.

**Comment by RonWilkinson** [comment]
Hello Kelly,

How are you progressing on adding optional parameters to QuickUMLS (#107) and allowing overlapping Spans (#97)?  I am eagerly awaiting both!

--Ron Wilkinson

**Comment by burgersmoke** [comment]
Hi @RonWilkinson  I apologize I did not reply to this sooner.   I've had a number of things come up unexpectedly and have not had enough free weekend time to get back to this.  I still have this on my radar.  It's just slipped several weeks.  I cannot make any promises, but I will try to carve out some time in the next few weeks to address #107 and #97.

I'll keep you posted and it would be great if you could "beta test" on a branch once I have these ready.

**Comment by burgersmoke** [comment]
I finally have a PR ready for this one.  I did not follow this recommendation exactly, but I think my approach is a bit simpler and easy to maintain given our vision for QuickUMLS with respect to medspacy.

Thank you for your patience on this @RonWilkinson!

A new medspacy release with this will be coming soon, but let me know if you'd like to test it earlier.

**Comment by burgersmoke** [comment]
This is now addressed with medspacy 1.0.0. If there are items identifies, please open new issues.
