### ISSUE TITLE
Compatible packages

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#110]
I upgraded to Anaconda3 2011.11 (Python 3.9.7 64-bit) and now the re-installation of MedSpaCy is failing with package incompatibilities.  Is there a latest recommended version of Anaconda and/or Python that you recommend for use with MedSpaCy?  I do want to use the one that supports SpaCy3.

**Comment by burgersmoke** [comment]
Thank you for the update @RonWilkinson . Our continuous integration is currently passing with Python 3.7.

Would it be possible for you to try 3.7 and see if this works for you?
