### ISSUE TITLE
**kwargs for QuickUMLS creation

### ISSUE THREAD

**Issue by kfujita-cohere** [medspacy/medspacy#112]
I am unable to create a PR here so would like to propose that the following is added:

https://github.com/medspacy/medspacy/blob/master/medspacy/util.py#L27
`def load(model="default", enable=None, disable=None, load_rules=True, quickumls_path=None, **kwargs):`

https://github.com/medspacy/medspacy/blob/master/medspacy/util.py#L72
comment something like: `**kwargs: QuickUMLS keyword arguments (see QuickUMLS in core.py in QuickUMLS repo)`

https://github.com/medspacy/medspacy/blob/master/medspacy/_quickumls.py#L6
`def create_quickumls(nlp, name="medspacy_quickumls", quickumls_path=None, **kwargs):`

https://github.com/medspacy/medspacy/blob/master/medspacy/_quickumls.py#L26
`quickumls_component = SpacyQuickUMLS(nlp, quickumls_path, **kwargs)`

Would be helpful to have these so we can pass through `overlapping_criteria`, `threshold`, `window`, `similarity_name`.

**Comment by kfujita-cohere** [comment]
@burgersmoke related to https://github.com/medspacy/medspacy/issues/107

**Comment by burgersmoke** [comment]
I finally have a PR ready for this one.  I did not follow this recommendation exactly, but I think my approach is a bit simpler and easy to maintain given our vision for QuickUMLS with respect to medspacy.  Thank you for your patience @kfujita-cohere 

A new medspacy release with this will be coming soon, but let me know if you'd like to test it earlier.

**Comment by burgersmoke** [comment]
This has now been resolved in medspacy 1.0.0.  All QuickUMLS arguments should now be supported when using a `config` dictionary when creating the component with `add_pipe()`.
