### ISSUE TITLE
version for requests dependency

### ISSUE THREAD

**Issue by gkennos** [medspacy/medspacy#113]
I had a look for a history or rationale for the restriction on version <2.16 for the requests dependency in setup.py and couldn't find anything, nor could I see anything in the release history of the requests library for versions 2.17+ that would explain it.  

Would it be possible to expand this to include up to <=2.19 for compatibility with huggingface datasets library?

**Comment by burgersmoke** [comment]
Yes, I think we can do this.  We've had some dependency issues with some of spacy's dependencies, but I will assess if this is feasible.

**Comment by burgersmoke** [comment]
@gkennos Sorry it took some time to come back with a response, but we have removed the dependency for `requests` from our setup.py.  It should be possible to use later versions like you mention is you use medspacy 1.0.0.

If you still have issues with doing this in medspacy 1.0.0, could you please re-open this ticket?
