### ISSUE TITLE
Vital Signs or Lab Results?

### ISSUE THREAD

**Issue by mkeywood1** [medspacy/medspacy#127]
Firstly, loving the medspacy project - it's awesome!! Thanks for putting it together.

I have a question though, and if this is not the right forum please could you point me towards something more suitable.

Do you have any sample projects to extract Vital Signs or Lab Results?
I'm thinking something like:
PHYSICAL EXAMINATION:  Blood pressure 146/91, pulse 76.  Normal conjunctivae.  Ears, nose, throat normal.  Neck is supple.  Chest clear.  Heart tones normal.  Abdomen soft.  Positive bowel sounds.  No hepatosplenomegaly.  No adenopathy in the neck, supraclavicular or axillary regions.  Neurologically alert.  Cranial nerves are intact.  Strength is 5/5 throughout.
LABORATORY WORK:  White blood count 10.4, hemoglobin 16, platelets not noted.  Sodium 137, calcium 9.1.

My initial thoughts are Target Match to get the Reading / Measurement, and a Context Rule to find the associated 'thing' that has been measured, but I wondered if this is the kind of thing you have any examples of, and any better suggestions as to how to approach it?

Thanks

**Comment by abchapman93** [comment]
Hi, thanks for your comments about medspaCy and sharing what you're working on! I think your approach sounds like a good one, but I don't know of any specific examples that already exist for this. @turbosheep this seems like the kind of work you guys may have done before?

**Comment by mkeywood1** [comment]
Thanks Alec.
Yes if anyone has any ideas / suggestions, I'd appreciate it. In the meantime I'll try my initial idea.
Thanks

**Comment by mkeywood1** [comment]
Thanks @patrickthealba. That is really useful.
I've only had a quick look but that looks really helpful re rules and terms, as you say.
Much appreciated :)
