### ISSUE TITLE
Notebook 1 - Introduction needs a few corrections for medspacy 1.0.0

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#164]
I have installed medspacy 1.0.0 in a python 3.9 environment.  To check out the new version, I have started to run through the notebooks.  In "Notebook 1 - Introduction", I had to modify the section about using medspacy with scispacy models to get it to work.  In particular, 

1. I had to install scispacy model en_core_sci_sm **v0.5.1** instead of the specified v0.2.5 to avoid install errors.
2. I had to correct the typos in the next two notebook cells that loaded en_core_web_sm instead to en_core_sci_sm to illustrate the use of the scispacy moded with medspacy.

**Comment by burgersmoke** [comment]
@turbosheep  I will assign this to myself since I'm updating some other notebooks to use scispacy 0.5.1 as well.

**Comment by burgersmoke** [comment]
@patrickthealba  let's get this one assigned to someone on your team.

**Comment by jianlins** [comment]
Fixed [here](https://github.com/medspacy/medspacy/pull/273)
