### ISSUE TITLE
Are you aware that spaCy actually supports regex pattern matches via the REGEX operator?

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#166]
The medspaCy notebook documentation still says that spaCy does not support regular expression matching and shows the medspaCy TargetRule addition to SpaCy matching that allows this.   Actually, spaCy pattern matching does support regex expressions.  Here is a screenshot of the relevant spaCy documentation:

![image](https://user-images.githubusercontent.com/11411901/198342347-35d76712-a634-4c9b-905e-246d5e932277.png)

The url to this in spaCy is:  [https://spacy.io/usage/rule-based-matching#adding-patterns](url)

**Comment by turbosheep** [comment]
We might need to update phrasing to make it more clear, but the spacy `REGEX` operator only matches on one token at a time, just like all their other pattern functionality. Our extended regex functionality allows using regexes on the raw text that may span more than one token. 

spacy describes some of this functionality here: https://spacy.io/usage/rule-based-matching#regex-text

They suggest using `Doc.char_span()` to resolve multi-word regex matches, however `char_span` returns `None` when the regex match does not align with token boundaries. This was not particularly useful and ended up throwing out matches frequently if they were misaligned by even one character. 

Medspacy's RegexMatcher has snapping schemes so it will attempt to create a span based on the char indexes identified regardless of whether they actually align with spacy's tokens. This _can_ create some unintended behavior when you end up with an unintended span, but we found it to be a useful addition overall.

**Comment by RonWilkinson** [comment]
Thanks very much for the explanation!  I think it would be useful to note the existence of both options with their differences in the notebook documentation.  I can imagine cases, for example, in which one might want to strictly align matches with token boundaries a la spaCy as well as ones where one would not.
