### ISSUE TITLE
Can't Install medspacy on Windows

### ISSUE THREAD

**Issue by anshupolestar** [medspacy/medspacy#168]
I am not able to install the medspacy library on windows because It's throwing error with leveldb. The error message says 
`Don't know how to compile leveldb for Windows!`. 
Also I tried to use it with google colab, but colab uses python 3.6 and python 3.6 doesn't support '**Literal**', so it's throwing an Import Error. 
Please help me around it.

**Comment by anshupolestar** [comment]
Used setup.py file to install and it worked

**Comment by ivantyj** [comment]
@anshupolestar 
Same problem here.  Installation on Windows through `pip install` is broken now.
I've successfuly installed medspacy through `pip install medspacy` on Oct 21, but failed now while trying to install in a new virtualenv.
I guess it is caused by the wheel file uploaded on Oct 26 ([medspacy-1.0.0-py3-none-any.whl](https://files.pythonhosted.org/packages/ac/23/f379ec8aa33f35428b45df101855d5c4c1b9157113ca7d644c3b1339612f/medspacy-1.0.0-py3-none-any.whl) ).  
Hope you can reopen the issue notifying devs to fix this, thanks.

**Comment by ivantyj** [comment]
A better workaround is to install using `--no-binary` , for example:
`pip install medspacy --no-binary medspacy`
or 
`pip install -r requirements.txt --no-binary medspacy`
Will bypass using medspacy's wheel file and install from dist source on PyPi.

**Comment by anshupolestar** [comment]
Thanks @ivantyj will try your solution, as after installing using setup.py file medspacy is not working.
I have raised an issue regarding that also [Link for that issue](https://github.com/medspacy/medspacy/issues/169). Please let me know if installation using `--no-binary` is working fine.

**Comment by burgersmoke** [comment]
Yes, I am trying to figure out how this is happening.  When we released the 1.0.0 version, a pip install was working fine on Windows and now it is not. 

For now, I agree with the workaround to check out the repo (or download a ZIP of it) and run this from the location of your medspacy repo:

`python setup.py install`

Can you try this and see if it resolves your issue?

As a side note for anyone interested, `leveldb` was once a dependency for `medspacy_quickumls` but we removed this dependency in the last release.  So I'm trying to figure answers to the following questions.  I'm open to any ideas from users or developers of medspacy:

1. This is an older dependency for medspacy_quickumls , but on line 12 of our setup.py I already had code which should prevent medspacy_quickumls from attempting to install.  Anyone have any ideas on why this might work properly for python setup.py install and not for a pip install? (FYI: https://github.com/medspacy/medspacy/blob/master/setup.py#L12)
2. Further, even if medspacy_quickumls attempts to install, I removed leveldb as a dependency (and even as an option) with several tickets.  Is it possible I may have published medspacy while I had an older version of medspacy_quickumls in my environment?
3. Any ideas on why this started recently (past 2-3 weeks) while when we released a pip install would work fine on Windows?

**Comment by burgersmoke** [comment]
Meanwhile, I will continue to track the issue here:

#173

**Comment by burgersmoke** [comment]
For anyone who wants to test this early, could you try this on Windows and let me know if this works for you?

`pip install medspacy>=1.0.1`

**Comment by burgersmoke** [comment]
OK, this appears to be working now with 1.0.1 which was just merged into master.

**Comment by bwang482** [comment]
> OK, this appears to be working now with 1.0.1 which was just merged into master.

Does 1.0.1 still exist? Pip doesn't seem to find it.
