### ISSUE TITLE
Set up CI that medspacy is continually able to 'pip install'

### ISSUE THREAD

**Issue by burgersmoke** [medspacy/medspacy#17]
In a team discussion, we agreed that it would be great to have CI that ensures periodically (maybe every push?) that this runs without problem:

```pip install medspacy```

**Comment by turbosheep** [comment]
This is complete now. 🎉

**Comment by burgersmoke** [comment]
I was not very clear in my intent on this one.  While we now currently are able to run `pip install medspacy`, I want to set up CI that this will alert us if this ever fails.  

So I'll re-open this one so that I can set up CI for this as we do not have it presently.

**Comment by burgersmoke** [comment]
This is now working.  @jianlins  set this up.   The workflow file is here:
https://github.com/medspacy/medspacy/blob/master/.github/workflows/manual_test_pip.yml

Here is an example of a successful execution:

https://github.com/medspacy/medspacy/actions/runs/4347089766
