### ISSUE TITLE
How to constrain TERMINATE in specific category

### ISSUE THREAD

**Issue by bwang482** [medspacy/medspacy#171]
I have a termination point defined by "," as below, and I want it to only apply to the `is_family` category. However, after some testing, it seems to apply to all other categories too, e.g. `is_hypothetical`. Is this as intended? 

```
    {
      "category": "FAMILY",
      "literal": ",",
      "direction": "TERMINATE"
    }
```

**Comment by abchapman93** [comment]
Currently, "TERMINATE" applies to all other modifier types. But this is an interesting idea and could be a good use case to address in the future, could definitely see this being useful in the future. 

Will close this issue for now but will keep this idea in our backlog so we could potentially add a feature addressing this.
