### ISSUE TITLE
Installation failure - leveldb for Windows

### ISSUE THREAD

**Issue by jangg007** [medspacy/medspacy#173]
I am getting this error when trying to install the latest version of medspacy. I am using python 3.8 in the environment. 
After doing some research I used python 3.6, the installation will be successful, but the import will fail with other modules

Here is the output from python 3.8 env.

(mspa4) C:\Users\jange>pip install medspacy==1.0.0
Collecting medspacy==1.0.0
  Using cached medspacy-1.0.0-py3-none-any.whl (146 kB)
Collecting spacy>=3.4.1
  Using cached spacy-3.4.3-cp38-cp38-win_amd64.whl (12.2 MB)
Collecting PyRuSH>=1.0.6
  Using cached PyRuSH-1.0.8-cp38-cp38-win_amd64.whl (63 kB)
Collecting medspacy-quickumls==2.6
  Using cached medspacy_quickumls-2.6-py3-none-any.whl (31 kB)
Collecting jsonschema
  Using cached jsonschema-4.17.1-py3-none-any.whl (90 kB)
Collecting pysbd==0.3.4
  Using cached pysbd-0.3.4-py3-none-any.whl (71 kB)
Collecting numpy>=1.8.2
  Using cached numpy-1.23.5-cp38-cp38-win_amd64.whl (14.7 MB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pytest>=6
  Using cached pytest-7.2.0-py3-none-any.whl (316 kB)
Collecting medspacy-simstring>=2.1
  Using cached medspacy_simstring-2.1.tar.gz (68 kB)
  Preparing metadata (setup.py) ... done
Collecting unqlite>=0.8.1
  Using cached unqlite-0.9.3.tar.gz (575 kB)
  Preparing metadata (setup.py) ... done
Collecting unidecode>=0.4.19
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting leveldb>=0.193
  Using cached leveldb-0.201.tar.gz (236 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      Don't know how to compile leveldb for Windows!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by burgersmoke** [comment]
Yes, I am trying to figure out how this is happening.  When we released the 1.0.0 version, a pip install was working fine on Windows and now it is not. 

For now, one workaround is to check out the repo (or download a ZIP of it) and run this from the location of your medspacy repo:

`python setup.py install`

Can you try this and see if it resolves your issue?

As a side note for anyone interested, `leveldb` was once a dependency for `medspacy_quickumls` but we removed this dependency in the last release.  So I'm trying to figure answers to the following questions.  I'm open to any ideas from users or developers of medspacy:

1. This is an older dependency for medspacy_quickumls , but on line 12 of our setup.py I already had code which should prevent medspacy_quickumls from attempting to install.  Anyone have any ideas on why this might work properly for python setup.py install and not for a pip install? (FYI: https://github.com/medspacy/medspacy/blob/master/setup.py#L12)
2. Further, even if medspacy_quickumls attempts to install, I removed leveldb as a dependency (and even as an option) with several tickets.  Is it possible I may have published medspacy while I had an older version of medspacy_quickumls in my environment?
3. Any ideas on why this started recently (past 2-3 weeks) while when we released a pip install would work fine on Windows?

**Comment by burgersmoke** [comment]
FYI: Issue #168 also has some very good information.  It looks like on Oct 21, the WHL file was correct, but now another WHL uploaded on Oct 26 appears to be expecting a dependency of `medspacy_quickumls`.

I'm going to try a fresh clone, build, and package to see if this dependency is still present.

**Comment by burgersmoke** [comment]
For anyone who wants to test this early, could you try this on Windows and let me know if this works for you?

`pip install medspacy>=1.0.1`

**Comment by burgersmoke** [comment]
OK, this appears to be working now with 1.0.1 which was just merged into master.

**Comment by jangg007** [comment]
Thank you @burgersmoke . The installation worked fine. 
But import is failing with this error - ModuleNotFoundError: No module named 'quicksectx.quicksectx'

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-6db48d3803fe> in <module>
      4 
      5 import spacy
----> 6 import medspacy

~\anaconda3\envs\mspa4\Lib\site-packages\medspacy\__init__.py in <module>
----> 1 from . import components
      2 from ._extensions import set_extensions, get_extensions, get_doc_extensions, get_span_extensions, get_token_extensions
      3 from ._version import __version__
      4 from .util import load
      5 

~\anaconda3\envs\mspa4\Lib\site-packages\medspacy\components.py in <module>
     10 }
     11 
---> 12 from .sentence_splitting import PyRuSHSentencizer
     13 from .target_matcher import TargetMatcher
     14 from .context import ConText

~\anaconda3\envs\mspa4\Lib\site-packages\medspacy\sentence_splitting.py in <module>
      1 import pysbd
----> 2 from PyRuSH import PyRuSHSentencizer
      3 from spacy.language import Language
      4 
      5 

~\anaconda3\envs\mspa4\Lib\site-packages\PyRuSH\__init__.py in <module>
     29 # limitations under the License.
     30 
---> 31 from .PyRuSHSentencizer import PyRuSHSentencizer
     32 from .RuSH import RuSH, BEGIN, END
     33 from .version import __version__

~\anaconda3\envs\mspa4\Lib\site-packages\PyRuSH\PyRuSHSentencizer.py in <module>
     19 from spacy.pipeline import Sentencizer
     20 
---> 21 from .RuSH import RuSH
     22 from .StaticSentencizerFun import cpredict, cset_annotations
     23 

~\anaconda3\envs\mspa4\Lib\site-packages\PyRuSH\RuSH.py in <module>
     33 from typing import Union, List
     34 
---> 35 from PyFastNER import FastCNER
     36 from PyFastNER import Span
     37 

~\anaconda3\envs\mspa4\Lib\site-packages\PyFastNER\__init__.py in <module>
----> 1 from .FastCNER import FastCNER
      2 from .IOUtils import IOUtils, Rule, Span
      3 from .version import __version__

~\anaconda3\envs\mspa4\Lib\site-packages\PyFastNER\FastCNER.py in <module>
     18 from typing import Union, List, Dict
     19 
---> 20 from quicksectx import IntervalTree, Interval
     21 
     22 from .IOUtils import IOUtils, Rule, Span

~\anaconda3\envs\mspa4\Lib\site-packages\quicksectx\__init__.py in <module>
      1 from __future__ import unicode_literals
----> 2 from .quicksectx import Interval, IntervalNode, IntervalTree, distancex
      3 from .version import __version__

ModuleNotFoundError: No module named 'quicksectx.quicksectx'

**Comment by burgersmoke** [comment]
Thank you for reporting this.  I can see that you reported this with #177  so I'll continue the conversation there since this is a separate issue from what was originally reported for this one.
