### ISSUE TITLE
Import failing with ModuleNotFoundError: quicksectx.quicksectx

### ISSUE THREAD

**Issue by jangg007** [medspacy/medspacy#177]
When importing latest version of medspacy (1.0.1), I am getting the below error

ModuleNotFoundError: No module named 'quicksectx.quicksectx'

see the details below

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-6db48d3803fe> in <module>
      4 
      5 import spacy
----> 6 import medspacy

~\anaconda3\envs\mspa4\Lib\site-packages\medspacy\__init__.py in <module>
----> 1 from . import components
      2 from ._extensions import set_extensions, get_extensions, get_doc_extensions, get_span_extensions, get_token_extensions
      3 from ._version import __version__
      4 from .util import load
      5 

~\anaconda3\envs\mspa4\Lib\site-packages\medspacy\components.py in <module>
     10 }
     11 
---> 12 from .sentence_splitting import PyRuSHSentencizer
     13 from .target_matcher import TargetMatcher
     14 from .context import ConText

~\anaconda3\envs\mspa4\Lib\site-packages\medspacy\sentence_splitting.py in <module>
      1 import pysbd
----> 2 from PyRuSH import PyRuSHSentencizer
      3 from spacy.language import Language
      4 
      5 

~\anaconda3\envs\mspa4\Lib\site-packages\PyRuSH\__init__.py in <module>
     29 # limitations under the License.
     30 
---> 31 from .PyRuSHSentencizer import PyRuSHSentencizer
     32 from .RuSH import RuSH, BEGIN, END
     33 from .version import __version__

~\anaconda3\envs\mspa4\Lib\site-packages\PyRuSH\PyRuSHSentencizer.py in <module>
     19 from spacy.pipeline import Sentencizer
     20 
---> 21 from .RuSH import RuSH
     22 from .StaticSentencizerFun import cpredict, cset_annotations
     23 

~\anaconda3\envs\mspa4\Lib\site-packages\PyRuSH\RuSH.py in <module>
     33 from typing import Union, List
     34 
---> 35 from PyFastNER import FastCNER
     36 from PyFastNER import Span
     37 

~\anaconda3\envs\mspa4\Lib\site-packages\PyFastNER\__init__.py in <module>
----> 1 from .FastCNER import FastCNER
      2 from .IOUtils import IOUtils, Rule, Span
      3 from .version import __version__

~\anaconda3\envs\mspa4\Lib\site-packages\PyFastNER\FastCNER.py in <module>
     18 from typing import Union, List, Dict
     19 
---> 20 from quicksectx import IntervalTree, Interval
     21 
     22 from .IOUtils import IOUtils, Rule, Span

~\anaconda3\envs\mspa4\Lib\site-packages\quicksectx\__init__.py in <module>
      1 from __future__ import unicode_literals
----> 2 from .quicksectx import Interval, IntervalNode, IntervalTree, distancex
      3 from .version import __version__

ModuleNotFoundError: No module named 'quicksectx.quicksectx'

**Comment by jangg007** [comment]
i am using python 3.8.15 and os is windows 10 pro

**Comment by jangg007** [comment]
any luck on this issue? @burgersmoke

**Comment by warhawkmonk** [comment]
you can do the installation via setup.py file given in the medspacy github
python.exe(path) setup.py(path) install 
in the terminal

**Comment by jangg007** [comment]
> you can do the installation via setup.py file given in the medspacy github python.exe(path) setup.py(path) install in the terminal

I tried this and still getting the same error when trying to import medspacy from the program

**Comment by warhawkmonk** [comment]
download miniconda:-https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
now install medspacy directly (pip install medspacy)
dont worry about the conflict

**Comment by warhawkmonk** [comment]
download miniconda:-https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
now install medspacy directly (python(miniconda path) -m pip install medspacy)
dont worry about the conflict

**Comment by burgersmoke** [comment]
This was fixed in previous releases of medspacy.
