### ISSUE TITLE
quickumls seems to be broken in latest release on pip

### ISSUE THREAD

**Issue by jmugan** [medspacy/medspacy#178]
I upgraded medspacy and now quickumls doesn't work.

I did this
```nlp = medspacy.load(medspacy_enable=["medspacy_quickumls"],quickumls_path=quickumls_fp)```

which looks like it should work, but I get the error

```ValueError: [E002] Can't find factory for 'medspacy_quickumls' for language English (en). This usually happens when spaCy calls `nlp.create_pipe` with a custom component name that's not registered on the current language class. If you're using a Transformer, make sure to install 'spacy-transformers'. If you're using a custom component, make sure you've added the decorator `@Language.component` (for function components) or `@Language.factory` (for class components).```
I don't see where this thing is declared for spaCy.

And then looking at the notebook 11a, I can't get that to work either. With the newest quickumls in pip `MEDSPACY_DEFAULT_SPAN_GROUP_NAME` is not in `quickumls.constants`.

I'm on Linux. Thanks for all of your great work.

**Comment by burgersmoke** [comment]
Thank you for reporting this.  I hope I did not fix the Windows issue with 1.0.1 and then break Linux.  Until we can reproduce this and address it, does downgrading to 1.0.0 work for you?

**Comment by jmugan** [comment]
Thanks for your response, I'll try that tonight. I would do `pip install medspacy==medspacy 1.0.0`?

**Comment by burgersmoke** [comment]
Yes, and that syntax is close.  I think it would be:

`pip install medspacy==1.0.0`

**Comment by jmugan** [comment]
Yep, downgrading worked, thanks!

**Comment by jmugan** [comment]
I think I might have had the wrong quickumls installed. I think this is declared in quickumls, specifically in the medspacy-quickumls for the pipeline component.
