### ISSUE TITLE
ERROR SAVING MEDSPACY MODEL - AttributeError: 'PyRuSHSentencizer' object has no attribute 'punct_chars'

### ISSUE THREAD

**Issue by hariprakashamk** [medspacy/medspacy#183]
Dear MedSpacy Team,
@abchapman93 
@burgersmoke 

I am facing issues in saving MedSpacy model in my local disk storage.
I am getting the same below error while using "to_disk" method and "to_bytes" method .
I am getting the error as AttributeError: 'PyRuSHSentencizer' object has no attribute 'punct_chars'.

![Screenshot from 2022-12-06 13-54-38](https://user-images.githubusercontent.com/42015729/205859390-e2058963-6a1c-4620-8634-c22834a8bf83.png)

Can you please try saving the medspacy model as per the screen shot and help in saving the medspacy model?
I am using python3.8 with Linux OS(20.04). 
Version for medspacy used: "medspacy==1.0.0"

Regards,
Hariprakasham

**Comment by hariprakashamk** [comment]
Hi all,
I got the solution to this isssue by Mr. @abchapman93 .

```
# Remove PyRuSH and save to disk
nlp.remove_pipe("medspacy_pyrush")
nlp.to_disk("path/to/save")

# Read back in and add PyRuSH
nlp2 = spacy.load("path/to/save")
nlp2.add_pipe("medspacy_pyrush", first=True)
print(nlp2.pipe_names)
```

It did work for me !
Thank you @abchapman93 !

**Comment by smathewvelocity** [comment]
Hi Hari
Were you able to use the new model though? I mean, suppose you train the first model on some list of medicines with an custom entity type, and saved to disk. When you load the new model, I am not getting the custom entity type anymore. Any suggestions?

Thanks,
Sam
