### ISSUE TITLE
Unable to serialize medspacy Doc object that contains Sections of None

### ISSUE THREAD

**Issue by wchen-cohere** [medspacy/medspacy#188]
When trying to serialize and deserialize medspacy doc that contains a Section object that doesn't belong to any sections (e.g. `Section(category=None at 0 : 0 in the doc with a body at 0 : 331 based on the rule None`), I was able to serialize the doc object, but had this error when deserializing it:

<img width="1256" alt="error" src="https://user-images.githubusercontent.com/87447259/210410376-2d0edfa9-898e-4834-8fd0-f0d77a7b2258.png">

**Comment by jianlins** [comment]
Apologies for the delayed response. Could you provide a complete piece of code that we can integrate into a test case?

**Comment by burgersmoke** [comment]
Any chance you could provide code to reproduce this @wchen-cohere ?  If not, we should probably close this since it's been here for awhile.

**Comment by wchen-cohere** [comment]
It's been a while so I'm not sure if I can find the code to reproduce this. Let's close this issue then.
