### ISSUE TITLE
Develop branch CI fails

### ISSUE THREAD

**Issue by abchapman93** [medspacy/medspacy#19]
After merging in changes from the merged-repos branch, the CI jobs failed. It looks to be something with the new package structure, but the tests succeed when run locally.

**Comment by turbosheep** [comment]
the full logs say its struggling to import context objects in the testing classes, i can try recreating the error in a new environment

**Comment by burgersmoke** [comment]
@turbosheep were you able to re-produce this in a new environment?

From the logs (https://github.com/medspacy/medspacy/runs/1336569895?check_suite_focus=true) it looks like there are two different import errors I see:

```E   ModuleNotFoundError: No module named 'medspacy.section_detection'```

```E   ModuleNotFoundError: No module named 'medspacy.context'```

**Comment by abchapman93** [comment]
Okay, I think I might know the error. I'm not sure how to see what the CI suite is running, but my guess is it's doing:
`pytest tests`

I think that running that command leads to path and import errors, such as when there are subpackages. Instead, I think doing:
`python -m pytest tests`

I can recreate the issue locally using the first command, and it's fixed using the second.
@burgersmoke @turbosheep Does this seem correct to you?

**Comment by turbosheep** [comment]
I was just testing it and thats exactly what I found. The CI workflow just runs `pytest` and produces all the errors but if you do `python -m pytest tests\` it does not. Weirdly enough `pytest tests\` also produces the errors. I guess we don't know something about how pytest specifies project roots?

as an aside, should we have jsonschema in the requirements? all my tests failed because it was missing that at first after running install. A yaml test is also failing on my end

**Comment by turbosheep** [comment]
It seems to have something to do with the PYTHONPATH variable and handling imports from nested folders. I don't know why some of them work and others don't BUT this link from the pytest documentation seems to be that an init file in the root pytest folder solves the problem as we get nested testing folders https://docs.pytest.org/en/stable/pythonpath.html

I just tested this and it worked myself so i can send in the commit to fix it

**Comment by burgersmoke** [comment]
It looks like this is passing now on Ubuntu and MacOS but currently failing on Windows.  I should be able to take a closer look later today.  Here is the failure a `pytest` time on Windows:

```
================================== FAILURES ===================================
_________________________ TestItemData.test_from_yaml _________________________

self = <tests.context.test_context_item.TestItemData object at 0x000002415EBCB160>
from_yaml_file = 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpztu69hc4\\test_modifiers.yaml'

    def test_from_yaml(self, from_yaml_file):
>       assert ConTextItem.from_yaml(from_yaml_file)

tests\context\test_context_item.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
medspacy\context\context_item.py:195: in from_yaml
    f0 = _get_fileobj(_file)
medspacy\context\context_item.py:193: in _get_fileobj
    return urllib.request.urlopen(_file, data=None)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\urllib\request.py:223: in urlopen
    return opener.open(url, data, timeout)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\urllib\request.py:526: in open
    response = self._open(req, data)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\urllib\request.py:549: in _open
    'unknown_open', req)
c:\hostedtoolcache\windows\python\3.6.8\x64\lib\urllib\request.py:504: in _call_chain
    result = func(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <urllib.request.UnknownHandler object at 0x00000241671F6E80>
req = <urllib.request.Request object at 0x00000241671F6BE0>

    def unknown_open(self, req):
        type = req.type
>       raise URLError('unknown url type: %s' % type)
E       urllib.error.URLError: <urlopen error unknown url type: c>

c:\hostedtoolcache\windows\python\3.6.8\x64\lib\urllib\request.py:1388: URLError
=========================== short test summary info ===========================
FAILED tests/context/test_context_item.py::TestItemData::test_from_yaml - url...
======================= 1 failed, 127 passed in 23.75s ========================
Error: Process completed with exit code 1.
```

**Comment by turbosheep** [comment]
Yes, I ran into this YAML issue on my computer as well, but have not looked into it yet. I figured merging the request to fix PYTHONPATH issue was worthwhile and then we can see what windows-specific error is out there for the yaml parser.

**Comment by abchapman93** [comment]
Since JSON is going to be our standard, I think we can remove the YAML writer from our tests. We can keep it in the repository, but I don't think it should cause a build to fail, particularly since it's a Windows specific error. I also removed pyyaml from the requirements, so users will need to install that package if they actually use the yaml functionality but not otherwise.

Tests are successful now

**Comment by burgersmoke** [comment]
Excellent.  Sounds like a good decision.  Thanks for lightening my load that I do not need to look into this currently.
