### ISSUE TITLE
Update CI to include more python versions

### ISSUE THREAD

**Issue by turbosheep** [medspacy/medspacy#201]
Add CI tests for 3.8-3.10 and (maybe) 3.11

**Comment by jianlins** [comment]
Added in dev branch

**Comment by burgersmoke** [comment]
Yes, @jianlins  has added this now and I see that all of these tests are running successfully for Python versions 3.8 to 3.10 in both the `develop` and `master` branches.

Here is an example of this running successfully on one of the branches:
https://github.com/medspacy/medspacy/actions/runs/4347089766

I will close this issue now.
