### ISSUE TITLE
Need to separate branches' CI  from master

### ISSUE THREAD

**Issue by jianlins** [medspacy/medspacy#204]
Current CI is triggered on pull_request or push on multiple branches, however, only the master branch's CI will be tested. 
We might need to isolate the trigger of each of the three branches and check out the corresponding branch for CI testing.

**Comment by burgersmoke** [comment]
OK, so it sounds like we actually ARE running CI on other branches.  But the workflow files of those branches (e.g., `develop`) is, but rather the revision in `master`.

**Comment by jianlins** [comment]
work atm close for now.
