### ISSUE TITLE
Should we mention all the context rules explicitly? 

### ISSUE THREAD

**Issue by Raghu17s** [medspacy/medspacy#21]
Hey,

I am interested in finding the context (negation, family, uncertain, past history, etc) of the medical text. 
As I was going through example notebooks, it was understood that these rules are given explicitly. 
Does it mean that all the rules we need to specify for the algorithm? Is it possible to print the output as given by clinspacy (which is mentioned on medspacy page? like (is_negated, is_family, is_historical, is_uncertain etc. )

Thank you.

**Comment by abchapman93** [comment]
Hi there!

I think I understand your question, but let me ask a couple of clarifications:
By "these rules are given explicitly", do you mean that context rules are provided with the package? If so, yes - there are a set of default rules which are loaded when you call either `medspacy.load()` or `ConTextComponent(nlp)` . But you can also add rules as needed to fit your data using `ConTextItem`.

As far as printing out the output like clinspacy, I agree that would be a useful. I think what I'd like to do and would be pretty simple is a function which takes a list of docs and returns a pandas DataFrame with entity attributes as columns. I think this is what clinspacy is doing. I'll create a feature request for tha. You can also access each of the entity attributes like this:
```python
for ent in doc.ents:
    print(ent, ent._.is_negated, ent._.is_family, ent._.is_historical, ent._.is_uncertain, ent._.is_future)
```

**Comment by Raghu17s** [comment]
Hey, 
Thanks for your suggestion. 
1. I got it the process. 
2. Converting to dataframe: Following code is capable of producing the dataframe
```
cols = ['Entity', 'Label', 'Negation', 'History', 'Family', 'hypothetical', 'Uncertain'] 
list_ents =  []
for ent in doc.ents:
    list_ents.append([ent.text, ent.label_, ent._.is_negated, ent._.is_historical, 
                      ent._.is_family, ent._.is_hypothetical, ent._.is_uncertain])

df_medspacy_results = pd.DataFrame(data = list_ents, columns = cols)
```

You have mentioed that `ent._.is_future` available, but its missing in current version. 
Pls guide the changes needs to be done. 

3. I have following text "No fever, nausea, and headache."
  its picking "fever" negation status as "false". This is bit strange.

**Comment by abchapman93** [comment]
I was mistaken about `is_future`, that has now been changed to `is_hypothetical`.

Regarding #3, could you send the specific code you're using? When I run this, "fever", "nausea", and "headache" are all negated:
```python
import medspacy
from medspacy.ner import TargetRule

from medspacy.visualization import visualize_ent, visualize_dep

nlp = medspacy.load()

target_matcher = nlp.get_pipe("target_matcher")

target_matcher.add([TargetRule("fever", "CONDITION"), TargetRule("nausea", "CONDITION"), TargetRule("headache", "CONDITION")])

text = "No fever, nausea, and headache."

doc = nlp(text)
for ent in doc.ents:
    print(ent, ent._.is_negated)
>> fever True
>> nausea True
>> headache True
```

**Comment by abchapman93** [comment]
I'm gonna close out this issue for now, but let me know if you're still running into problems and I'd be happy to help debug!
