### ISSUE TITLE
rush_rules.tsv issues

### ISSUE THREAD

**Issue by ccottingham-presinet** [medspacy/medspacy#210]
Hello:
We are experiencing some issues with the rush_rules.tsv

if you have a doc like 
sentence\n
space\n
sentence

it will think the above is all one sentence.

if you put another empty line in before the line with space it will properly detect sentence end
sentence\n
\n
space\n
sentence

this is also fine:
sentence\n
\n
sentence

if you put the empty line AFTER the line with a space it will also think its one sentence

is this the intended behavior?
if so how can one override this so it doesn't think a space on a new line in between two sentences is mid sentence?

**Comment by burgersmoke** [comment]
@jianlins  Do you have any thoughts about this?

**Comment by ccottingham-presinet** [comment]
Here is an example of one of the failing tests. I forgot to mention that the sentence that is failing does not end with a period. sorry about that . it has two spaces on first empty line. 
we have no way to ensure a sentence end in a period bc we receive  reports from the technician / physician in however they write them. 
[test_multi_line_headings.txt](https://github.com/medspacy/medspacy/files/10758275/test_multi_line_headings.txt)

**Comment by ccottingham-presinet** [comment]
@burgersmoke @jianlins 
Any insights on this would be greatly appreciated. Thanks

**Comment by ccottingham-presinet** [comment]
@burgersmoke @jianlins 
i had some more time to look through all of this and found a missing rule that when added helped resolve this issue.
i am posting here for anyone else as well as hoping it can get added to the base rush_rules.tsv

**Comment by jianlins** [comment]
Thanks for the suggestions and sharing your solutions. I think this is a more dataset-specific rule, which might not work for other notes. There are cases where we need to treat this pattern as a single sentence.

**Comment by ccottingham-presinet** [comment]
Sounds good. I guess this can be closed then
Only thing I am concerned about is retaining this note for anyone else experiencing the same issue. If I can help someone not spend a few hours figuring out that would be awesome.
