### ISSUE TITLE
TargetMatcher raises RuntimeWarning, crashes code

### ISSUE THREAD

**Issue by jkgenser** [medspacy/medspacy#220]
This code in the TargetMatcher I believe should be allowed to continue without halting program execution. However if there are overlapping spans -- in my case from an NER model that runs first -- then the TargetMatcher will actually raise and crash my program.

Should this be fixed to use `warnings` module instead of Raising?

https://github.com/medspacy/medspacy/blob/master/medspacy/target_matcher/target_matcher.py#L167

If I catch this in my client code in a try: except, it will stop execution right there and I believe I will miss any other rules that may be caught in the document. So this seems like a pretty bad bug?

Would something like below be more appropriate?

```
                    warnings.warn(
                        f'The result ""{span}"" conflicts with a pre-existing entity in doc.ents. This result has been '
                        f"skipped",
                        RuntimeWarning,
                    )
```

**Comment by jkgenser** [comment]
@burgersmoke (since you seem active here): I have a local fork that I've patched this in. Let me know if you agree I can open a PR.

**Comment by burgersmoke** [comment]
Yes.  I think that sounds like a good change.  I agree that `RuntimeWarning` stronger than needed.  Since we test changes in the `develop` branch in preparations for releases, could you set up a PR in that branch?

Then either myself, @turbosheep  or @jianlins  will review it and get it in.

**Comment by jkgenser** [comment]
Awesome. I've opened to address the issue: https://github.com/medspacy/medspacy/pull/231

**Comment by burgersmoke** [comment]
Thank you @jkgenser .  This has been merged into the `develop` branch now.  We're working on our next release, so this will be in the next release, but not sure when that will be released.

**Comment by jianlins** [comment]
close as it is resolved
