### ISSUE TITLE
Switch to medspacy_quickumls so that Windows can automatically install QuickUMLS

### ISSUE THREAD

**Issue by burgersmoke** [medspacy/medspacy#226]
With our next release, the goal is to make Windows automatically install QuickUMLS.  Prior releases have involved additional steps to get dependencies in place.  With recent changes to `medspacy_quickumls` (see more here: https://github.com/medspacy/QuickUMLS/issues/17), we should be able to automatically install QuickUMLS for Windows.

This should simplify many issues and make these features more available to Windows users.

Next step will be to make sure that all tests pass.

**Comment by jianlins** [comment]
I think it's done. The only lingering issue is the unqlite dependency install from pip. Close this thread for good :D
