### ISSUE TITLE
Medspacy Model saving and loading

### ISSUE THREAD

**Issue by sirisha-punnamraju** [medspacy/medspacy#243]
We are using MedSpacy model to recognize medical conditions and medications with some custom target rules. We are able to save the model by removing the medspacy_pyrush component. But we are not able to reload the trained model using medspacy.load(). If we load the trained model using spacy.load(), there is no error but the entities are not getting recognized. Could you please tell us the correct way of serializing the medspacy model so that we can reload it successfully?
we are using 
Medspacy - 1.0.1
spacy - 3.5.1

Thanks
Sirisha

**Comment by jianlins** [comment]
I think now you can save the model with medspacy_pyrush with the latest version, if that helps.

**Comment by jianlins** [comment]
I assume it is resolved. Otherwise, you can reopen it.
