### ISSUE TITLE
quicksectx-0.3.7/setup.py No such file or directory

### ISSUE THREAD

**Issue by Rob-Smith-HDT** [medspacy/medspacy#256]
I am trying to "python3 setup.py install" and I am receiving the following error.  Any thoughts on how to resolve it?

Thanks

I am on a Mac using vscode, I've tried python 3.11.4 and 3.10.12

Running quicksectx-0.3.7/setup.py -q bdist_egg --dist-dir /var/folders/r0/w5fnm8712j39_f5db5fgvlr40000gn/T/easy_install-c5yy9ryl/quicksectx-0.3.7/egg-dist-tmp-kevuj0d5
error: [Errno 2] No such file or directory: '/var/folders/r0/w5fnm8712j39_f5db5fgvlr40000gn/T/easy_install-c5yy9ryl/quicksectx-0.3.7/requirements.txt'

**Comment by Janetxxx** [comment]
I got same error.

**Comment by jianlins** [comment]
Did you use pip install medspacy?

**Comment by jianlins** [comment]
Anyway, I will publish a new version of quicksectx, which includes requirements.txt in package.

**Comment by Janetxxx** [comment]
> Did you use pip install medspacy? Looks like it passes all the pip install tests. https://github.com/medspacy/medspacy/actions/runs/6578897281

Yes, I used pip install medspacy.

**Comment by jianlins** [comment]
Can you try it again?

**Comment by Rob-Smith-HDT** [comment]
Hi @jianlins thank you that now works.
