### ISSUE TITLE
Medspacy dependency/install cleanup

### ISSUE THREAD

**Issue by turbosheep** [medspacy/medspacy#275]
In the ongoing effort to keep medspacy stable and reduce the number of installation issues across different platforms and when dependencies update.

@abchapman93 mentioned cleaning up dependencies:
- Less stable components pushed out to optional installs
  - Pyrush + java dependencies sometimes cause issues
  - QuickUMLS has had a lot of work performed, but db dependencies still have occasional problems
- remove components that are no longer used, if any exist
  - leveldb???

@burgersmoke mentioned
- potentially create anaconda template yaml files for "easy" setup, potentially for OHDSI

Others potentially looking into build system updates such as Poetry.

**Comment by jkgenser** [comment]
Would the team consider updating the spacy requirement from `<3.6`? This prevents using features from 3.6 or 3.7

**Comment by jianlins** [comment]
Yes. We would like too. However, spaCy versions run too fast, and has back compatibility issues. It's a hard decision to choose the best base version. Any suggestions are welcome.

**Comment by jkgenser** [comment]
> Yes. We would like too. However, spaCy versions run too fast, and has back compatibility issues. It's a hard decision to choose the best base version. Any suggestions are welcome.

My suggestion is to start by CI testing on multiple versions, tracking issues, add handling (e.g. based on spacy version) depending on new spacy version for particular issues. There shouldn't be more than a small handful of exceptions.

It is semantic version so it shouldn't be too many backwards compat issues if using the public API.

**Comment by burgersmoke** [comment]
@jianlins  I think we should discuss this in our next medspacy developer meeting.  I think the main reason we put the limitation was because of 4.x development of spacy.  I think we should try changing the criteria to  `<4.0` and checking if we will have any issues.  I would think we might have no issues.

But we should probably open this up into a new issue since it's more specific than our general dependency cleanup.

**Comment by jianlins** [comment]
I know spansgroup is an issue between early 3.x and later 3.x versions.

**Comment by burgersmoke** [comment]
@jianlins  Just following up on this.  Wasn't there an analysis you had done to check which versions of spacy are currently working with medspacy?

Was there a ticket for that?  Or something we could reference here?

**Comment by jianlinshi** [comment]
I think it is not an issue any more in recent two versions.

**Comment by jianlins** [comment]
I think it is no an issue any more in recent two versions
