### ISSUE TITLE
What does MedSpacy contain that in not in SciSpacy?

### ISSUE THREAD

**Issue by borisdev** [medspacy/medspacy#280]
What's in MedSpacy that is not in SciSpacy?

Just paste a URL here or a few bullet points.

**Comment by borisdev** [comment]
https://www.phind.com/search?cache=yg2f5faoa8mem05ddadm24ar

**Comment by borisdev** [comment]
You can copy and paste Phind's answer in your README?

**Comment by jianlins** [comment]
Good question! SciSpacy primarily focuses on developing and releasing trained machine learning (ML) models for the general biomedical field. In contrast, medspacy primarily focuses on a rule-based approach, which is suitable for simpler, faster clinical natural language processing (NLP) tasks. 

Additionally, some clinical NLP tasks involve user requests to fix errors related to specific cases. These tasks are typically difficult for ML models to handle.
