### ISSUE TITLE
documentation to this library

### ISSUE THREAD

**Issue by shyamcody** [medspacy/medspacy#29]
Hi, I am a spacy user and was looking to explore this library. But I can't find any written documentation and it will take significantly more time to explore the code from source. Is there any written guide for this library or any documentation other than the made with medspacy projects? Any help would highly be appreciated.

**Comment by shyamcody** [comment]
I found out the notebooks just now..that seems to have enough documentation to start with.

**Comment by abchapman93** [comment]
Yes, we do hope to add more formal documentation in the near future, but for we hope that the notebooks are useful for learning how to work with the library. If you have any specific questions, feel free to let us know and we'd be happy to help!
