### ISSUE TITLE
Resources for Abbreviation Disambiguation in MedSpaCy?

### ISSUE THREAD

**Issue by dagmawinegesse12** [medspacy/medspacy#300]
Hello MedSpaCy Team,

I am currently exploring the use of MedSpaCy for processing medical texts and am particularly interested in the AbbreviationDetector component. I am looking to understand better the resources used for disambiguation of abbreviations, such as dictionaries or other structured forms that might be involved in this process.

Could you provide details on the following:

1. Does MedSpaCy utilize a specific dictionary or database for mapping abbreviations to their expanded forms?

2. If such a resource exists, is it available for review or export? I am interested in examining how comprehensive and up-to-date it is.

3. Additionally, any guidance on how the system handles disambiguation of abbreviations in varied contexts would be greatly appreciated.

Thank you in advance!!

**Comment by burgersmoke** [comment]
Hi @dagmawinegesse12 .  You mention a component called "AbbreviationDetector".  We do not have anything like this in medspacy.  We've talked about maybe trying to develop something like this, but currently we have nothing so the answer to this is short.

Perhaps you are thinking of scispacy and their AbbreviationDetector?

https://github.com/allenai/scispacy
