### ISSUE TITLE
installing medspacy in a clean environment leads to a numpy binary compatibility error when importing

### ISSUE THREAD

**Issue by barney-ellis** [medspacy/medspacy#305]
When I install medspacy in a clean environment (Python 3.11) and try importing it in a script, I get a binary incompatibility error. I believe this is because the spacy dependency is still pinned to <3.6, which is constrained to older version of thinc:

![image](https://github.com/user-attachments/assets/3f25ff98-71f6-4ae8-93ce-1925ef11eb76)

Pinning spacy to the latest version (3.8.2) fixes this issue for me. Has anyone else experienced this issue?

**Comment by burgersmoke** [comment]
We're looking into this, but it could be related to this:
https://github.com/explosion/spaCy/issues/13669

**Comment by burgersmoke** [comment]
@barney-ellis can you tell us which version of numpy is installed in your environment?

**Comment by burgersmoke** [comment]
It looks like our continuous does fail with this error.  So we might consider allowing newer version of spacy now:

https://github.com/medspacy/medspacy/actions/runs/11505912339/job/32028669661

**Comment by barney-ellis** [comment]
Thanks @burgersmoke, when I install medspacy using pip in a python 3.11.5 environment my numpy version is 2.1.2 and I get the above error. Pinning spacy to 3.8.2 my numpy version is 2.0.2 and I no longer get the error

**Comment by jianlins** [comment]
I believe this is resolved with our latest release 1.3.1. Close this issue.
