### ISSUE TITLE
unable to run medspacy.sentence_splitter

### ISSUE THREAD

**Issue by aniyazngn** [medspacy/medspacy#311]
Can someone tell me what i am doing wrong here , trying to use this model for the first time 
it is giving me error with the following code 

import medspacy
from medspacy.section_detection import Sectionizer
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

try:
    nlp = medspacy.load()

    sectionizer = nlp.add_pipe("medspacy_sectionizer", last=True)
    sectionizer.add([{"section_title": "Assessment and Plan", "category": "Assessment"}])

    logger.info(f"Loaded MedSpaCy pipeline components: {nlp.pipe_names}")
except Exception as e:
    raise RuntimeError(f"Failed to initialize MedSpaCy pipeline: {e}")

# Init
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI()

class UserRequest(BaseModel):
    text: str

@app.get("/")
def root():
    """
    Root endpoint to confirm the API is running.
    """
    return {"message": "MedSpaCy-based clinical NLP API is running!"}

@app.post("/process_text")
def process_text(user_request: UserRequest):
    """
    Process clinical text using MedSpaCy's pipeline without QuickUMLS.
    """
    try:
        text = user_request.text
        response = {"original_text": text, "components_run": []}

        doc = nlp(text)

        entities = [{"text": ent.text, "label": ent.label_} for ent in doc.ents]
        if entities:
            response["components_run"].append("entity_recognition")
            response["entities"] = entities

        sections = [{"title": section.title, "text": section.text} for section in doc._.sections]
        if sections:
            response["components_run"].append("section_detection")
            response["sections"] = sections

        if not entities and not sections:
            response["message"] = "No relevant components detected in the provided text."

        return response

    except Exception as e:
        logger.error(f"Error processing text: {e}")
        raise HTTPException(status_code=500, detail=f"Error processing text: {e}")

**Comment by jianlins** [comment]
Try this: 
https://github.com/medspacy/medspacy/blob/master/notebooks/section_detection/1-Clinical-Sectionizer.ipynb
