### ISSUE TITLE
Add negation location to negex outputs

### ISSUE THREAD

**Issue by MichalMalyska** [medspacy/medspacy#41]
It would probably be a good idea to show not just which entities where negated, but what was the trigger for the negation. This should not be too much of a problem since the matcher returns the position and all that is needed is to persist that.

**Comment by abchapman93** [comment]
Great point. There is a way to get this by looking at an entity's modifiers, although it's not based on specific attributes. Does the snippet below get you the info you're looking for?

```
doc = nlp("There is no evidence of pneumonia.")
for ent in doc.ents:
    print(ent, ent._.is_negated)
    for modifier in ent._.modifiers:
        print(modifier, modifier.category)
```

**Comment by MichalMalyska** [comment]
Yeah, I realized I was looking at the old version of medspacy with the original negex instead of the context. Thanks!
