### ISSUE TITLE
Python 3.6 incompatibility with re.Pattern in preprocessor

### ISSUE THREAD

**Issue by turbosheep** [medspacy/medspacy#54]
If we want to add python 3.6 compatibility back to medspacy, need to fix typechecking of compiled regex patterns in the preprocessor.

**Comment by burgersmoke** [comment]
Python 3.6 and Python 3.7 are longer supported in medspacy as of release 1.0.0.

@turbosheep  I am going to close this issue, but I believe you told me about this issue and this change to not support 3.6 and 3.7 was an intentional decision for 1.0.0.
