### ISSUE TITLE
Keep failing medspacy.load()

### ISSUE THREAD

**Issue by jooyeongkang** [medspacy/medspacy#56]
I tried to use medspacy, but I'm not able to do from the beginning as below:

![Screen Shot 2021-03-31 at 12 19 59 AM](https://user-images.githubusercontent.com/42654506/113094173-d6dfd200-91b6-11eb-9b6e-55ebf6440cda.png)

**Comment by abchapman93** [comment]
Hi there - I think I've seen this with of spaCy 3.*, which we don't currently support (but are working on it). Could you check what version of spacy you have installed? 

In the meantime, if that isn't the issue you could fix the tokenizer-specific issue by calling `medspacy.load(disable=["tokenizer"])` which will just use the default spaCy tokenizer.

**Comment by burgersmoke** [comment]
@abchapman93  is correct on this.  I just investigated the differences on the member `nlp.Defaults,infixes` and it is a different type between spacy 2.x and 3.x.  For now, our recommendation is to use spacy 2.x since we do not yet support 3.x. Even if this one issue were to be resolved, all other behavior has not yet been tested.  

Here's more info on how I saw this difference:

spacy 2.x:
```
(spacy2) C:\Users\slick>python
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.__version__
'2.3.5'
>>> nlp = spacy.load('en_core_web_sm')
>>> type(nlp.Defaults.infixes)
<class 'tuple'>
>>>
```

spacy 3.x
```
(spacy3) C:\Users\slick>python
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> spacy.__version__
'3.0.5'
>>> nlp = spacy.load('en_core_web_sm')
>>> type(nlp.Defaults.infixes)
<class 'list'>
>>>
```

**Comment by sandertan** [comment]
Hi @abchapman93 and @burgersmoke , I also encountered this issue in spaCy 2.3.2 using a Dutch spaCy model. Clean conda environment, installed medspacy and `nl_core_news_sm`, tested in both Python 3.7.10 & 3.8.10.

Adding `disable={'tokenizer'})` indeed solved it. `nlp.Defaults,infixes` is a list in this version.

```
(medspacy-test) stan3@macbook Data % python
Python 3.7.10 (default, Feb 26 2021, 10:16:00) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> print(spacy.__version__)
2.3.2
>>> import medspacy
>>> print(medspacy.__version__)
0.1.0.2
>>> nlp = medspacy.load("nl_core_news_sm", disable={"ner", 'tokenizer'})
------ lots of these deprecation warnings ----------
/Users/stan3/miniconda3/envs/medspacy-test/lib/python3.7/site-packages/catalogue.py:138: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
  for entry_point in AVAILABLE_ENTRY_POINTS.get(self.entry_point_namespace, []):
----------------------------------------------------
>>> type(nlp.Defaults.infixes)
<class 'list'>
```
