### ISSUE TITLE
Plan to make medspacy work with spacy 3.0

### ISSUE THREAD

**Issue by MichalMalyska** [medspacy/medspacy#62]
are there currently any plans on making medspacy compatible with the 3.0 release?

**Comment by MichalMalyska** [comment]
or at least, do you guys know what will not work with 3.0 without major changes ?

**Comment by abchapman93** [comment]
We did start looking at this a while ago and made a branch where we started drafting some of the changes that would be needed: https://github.com/medspacy/medspacy/tree/spacy-v3 

One of the biggest impacts to medspaCy is that the way custom components are added to a pipeline is completely changed, so I think each of our components would have to reconfigured using spaCy's V3 architecture. So it is a bit of a lift.

But there is increasing interest in using spaCy 3, so we should probably make this a priority. I'll revisit this topic this week and see if we could feasibly release something in the next few weeks.

**Comment by MichalMalyska** [comment]
That is great to hear! I'm assuming this wouldn't mean large changes to how components like sectionizer or context work?

**Comment by turbosheep** [comment]
Ideally it would involve no changes to how any of the components other than how they are added to a pipeline.  As far as I understand it, the changes from a user perspective from spacy 2.x to spacy 3.x are fairly minimal. 

It will involve changing the class definitions and familiarizing ourselves with the component registry inside spacy itself, but I do not believe any of the API or results' data structures would need to change.

**Comment by MichalMalyska** [comment]
In which case, I have a bunch of patterns to add to the sectionizer, is that something you guys are interested in, or should I just keep it local ?

**Comment by turbosheep** [comment]
We would be happy to accept any patterns you have developed if you want to submit a pull request.

**Comment by jmugan** [comment]
Hi, any update on spacy 3.0?

**Comment by burgersmoke** [comment]
Good question @jmugan.  This is still being planned, but we do not have an ETA yet.  The good news is that much of the work is done but there remains some additional testing.  Given that spacy 3.x is not yet supported, I am re-opening this issue.

**Comment by abchapman93** [comment]
medspaCy 0.2.0.0 is now published and compatible with spaCy 3! Thanks everyone for your patience.
