### ISSUE TITLE
Target Matcher Rule Question

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#71]
Given that the tokenization for text "95 °F" is [95, °, F], I would expect both of the rules in this test code to work.  

- The first rule correctly identifies "95 °" as a temperature entity.  
- The alternate rule should detect "95 °F" as a temperature entity, but it does not detect the text as matching.  

Am I doing something wrong or is there a bug?

![image](https://user-images.githubusercontent.com/11411901/119874228-6376ea00-bef3-11eb-93c7-26fb6fd25814.png)

**Comment by RonWilkinson** [comment]
Never mind, I see my mistake.

**Comment by burgersmoke** [comment]
OK, I was about to comment about the LOWER here and the list being uppercase values.  I presume that the TargetRules are behaving as expected.
