### ISSUE TITLE
PyRush sentence splitter really struggles with lists

### ISSUE THREAD

**Issue by MichalMalyska** [medspacy/medspacy#73]
I can see this quite often in clinical text where a list like:

Consult:
-2-day history of X
-today Y
-history of Z a few years ago 
-Symptom 1: none
-Symptom 2: none

gets processed wrong by PyRUSH:

```
text_listicle = "Consult\n-2-day history of X\n-Today Y\n-history of Z a few years ago \n-Symptom A: None \n-Symptom B: None\n\n"
for sent in nlp(text_listicle).sents:
    print(sent)
    print(len(sent))
```

gives:

```
Consult
-2-day history of X
-Today Y
-history of Z a few years ago 
20
-Symptom A: None 
5
-Symptom B: None
5
```

Versus using PySBD:

```
Consult
2
-2-day history of X
7
-Today Y
3
-history of Z a few years ago 
8
-Symptom A: None 
5
-Symptom B: None
5
```

I could submit a PR with adding PySBD as a spacy 3.0 component since I have it ready if you guys would like (since their repo does not have spacy 3.0 support out of the box right now)

**Comment by abchapman93** [comment]
Thanks, I saw your pysbd merge, that's awesome!
@jianlins is the developer of PyRuSH, do you have any recommendations for users facing the issues above?

**Comment by burgersmoke** [comment]
This is a great addition and the example here is good motivation.  Thanks again @MichalMalyska !
