### ISSUE TITLE
'ConTextComponent' object has no attribute 'item_data'

### ISSUE THREAD

**Issue by abhibisht89** [medspacy/medspacy#77]
Getting below error on running the code from one of the notebook (https://github.com/medspacy/medspacy/blob/master/notebooks/01-Introduction.ipynb):

import spacy
nlp2 = spacy.load("en_core_web_sm", disable={"ner"})
nlp2 = medspacy.load(nlp2)
nlp2.pipe_names
context = nlp.get_pipe("context")
context.item_data[:10]

**ERROR**:
---------------------------------------------------------------------------
**AttributeError                            Traceback (most recent call last)
<ipython-input-16-456754c8375f> in <module>
----> 1 context.item_data[:10]

AttributeError: 'ConTextComponent' object has no attribute 'item_data'**

**Comment by abchapman93** [comment]
Ah, looks like this notebook isn't updated to match the newer syntax. You can change this line to `context.rules[:10]` and it should work.
