### ISSUE TITLE
Would like suggestion for implementing (if necessary, an equivalent to) overlapping entities

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#78]
The following text is a fragment of a clinical note:

"HEENT: Tympanic membranes are normal bilaterally. Oropharynx is normal, no exudate no erythema. Neck is supple no anterior cervical lymphadenopathy.  3+ kissing tonsils"

I have successfully defined "HEENT:" as a section title with the remaining text as the section body.  I want to do two things with the content of the section body.

1. Tag the individual whole sentences in the section body as spans of type "Medical_Condition"
2. Process the tokens in the section body using QuickUMLS to identify small components like anatomy and disease name.

I find that if I create custom spans for the whole sentences using an on_match function in the SectionRule for HEENT:, I can successfully get the "Medical_Condition" tags that I want.  However, doing so causes QuickUMLS skip processing of the tokens in the section body, perhaps because overlapping entities are not allowed or perhaps for some other reason.

Are there any suggestions for how to accomplish both of the things I want to do?

Thanks!

**Comment by abchapman93** [comment]
Reading your description above, I do think it might have to do with overlapping entities. spaCy explicitly doesn't allow any overlapping spans in `doc.ents`, and it sounds like what you're trying to do will necessarily include overlapping spans. But it sounds like you don't necessarily need QuickUMLS to add to doc.ents, but just to add attributes to certain tokens, right? I'm not super experienced with QuickUMLS, but @burgersmoke do you know if there's a way to use QuickUMLS separately from adding to doc.ents?

**Comment by RonWilkinson** [comment]
Should QuickUMLS  only be able to add to doc.ents, I could move my "Medical_Condition" tags to a custom doc attribute list.  However, would I be able to access my custom list via DocConsumer?  I would want to easily export my custom spans into a Pandas dataframe, ideally with the to_dataframe() method.

**Comment by burgersmoke** [comment]
OK, this has been made available now with medspacy 1.0.0.  But I'd like to make sure that my terminology is clear.  Spacy still does not allow overlapping entities.  At least not in `doc.ents`.  However, starting with spacy 3, SpanGroups can be used for all medspacy components.  This is not the default behavior, but it is available.  If enabled, medspacy components which "emit" text spans put them into a default named span group.  Similarly, if enabled, all components which "consume" spans, can consume text spans from the same named group.

For more info, please consult these release notes:
https://github.com/medspacy/medspacy/releases/tag/1.0.0
