### ISSUE TITLE
Question about sectionizer in case of incomplete SectionRules

### ISSUE THREAD

**Issue by sandertan** [medspacy/medspacy#80]
Hi, first of all, thanks for creating and open-sourcing this awesome module!

I was wondering how I should approach the problem of sectionizing a text with an incomplete list of SectionRules. For example: I'm only interested in a few sections, so I added SectionRules for those categories in my language. Currently, sections following my section of interest are also included in my section_span of interest. I could make a rule to catch those, but I expect that list could be quite long. Is there a way to put all other sections in an "other"-section? All my sections are separated by an empty line.

**Comment by abchapman93** [comment]
Hi! This is an issue I deal with pretty regularly and don't necessarily have a perfect solution to yet. One thing I do is take a sample of documents and run a regular expression pattern to match possible section titles (like `re.compile("[a-zA-Z]+:\n")` ), sort them by frequency, and then manually review them and add them to my SectionRules with a category of "other" or "unknown". 

You could also just write a catch-all SectionRule using a regular expression like the one above to match unknown sections, but that runs the risk of overwriting the section rules you've manually curated. For that reason I usually try to generate an explicit list of "Other" patterns.

**Comment by sandertan** [comment]
Thanks for the suggestions. I'll give it a try!
