### ISSUE TITLE
spacy version used in medspacy-v3?

### ISSUE THREAD

**Issue by bwang482** [medspacy/medspacy#83]
Hi, why in the `medspacy-v3` setup file `spacy>=2.3.0,<=2.3.2` is being instructed instead of spacy v.3? 

Thanks.

**Comment by burgersmoke** [comment]
At this time, medspacy is still compatible with spacy 2.3.x.  However, support for spacy 3.x is coming.  Cannot give an ETA yet, but this is likely to happen before the end of the year given an upcoming presentation on medspacy.

To follow this topic, here is the current issue:
https://github.com/medspacy/medspacy/issues/62

**Comment by bwang482** [comment]
Thanks both! I have noticed in the `spacy-v3-old` branch, `spacy>=3.0.1` is included in the setup file while in the `spacy-v3` branch, `spacy>=2.3.0,<=2.3.2` is used.

**Comment by jamaliki** [comment]
Hi, @abchapman93 are there any outstanding tasks left left to merge spacy-v3 to master?

**Comment by abchapman93** [comment]
@jamaliki at this point I think the main thing is just taking care of some version conflicts and updating the documentation. But we're starting to look at those issues and I think we should be very close!

**Comment by abchapman93** [comment]
medspaCy 0.2.0.0 is now published and compatible with spaCy 3! Thanks everyone for your patience.
