### ISSUE TITLE
Tokenizer conflict with spanish models

### ISSUE THREAD

**Issue by jcastanohiba** [medspacy/medspacy#88]
nlp = medspacy.load("es_core_news_sm", disable={"ner"})

throws an error:  line 32, in create_medspacy_tokenizer
    infixes = nlp.Defaults.infixes + (r'''[{}]'''.format(re.escape(punctuation_chars)),)
Only way it works is:
nlp = medspacy.load("es_core_news_sm", disable={"tokenizer"})
print(nlp.pipe_names) shows:
['tagger', 'parser', 'ner', 'target_matcher', 'context'], it is not shure which tokenizer is working.

**Comment by burgersmoke** [comment]
Thank you @jcastanohiba.  I will look into this in the next few days since we want to make sure that medspacy works in languages besides English.  Spanish, French and German are definitely on our list to ensure support.

**Comment by MichalMalyska** [comment]
This should be now fixed by PR #100
