### ISSUE TITLE
ConText model not supporting inputs other than entities

### ISSUE THREAD

**Issue by MichalMalyska** [medspacy/medspacy#90]
https://github.com/medspacy/medspacy/blob/1ce22f1e912d0231dd508ee18efa800a9a689f4d/medspacy/context/context_component.py#L133

This seems to be the only line that prevents the usecase. Is this a feature that was abandoned / deprecated ? It seems as long as the targets is a list of Span objects this should work.

**Comment by Jackyyao0205** [comment]
I have the same question!

**Comment by abchapman93** [comment]
Yeah this was an idea I'd originally had but never really needed. Once we get the spacy 3 changes in we could look at implementing this.

**Comment by MichalMalyska** [comment]
@abchapman93 I have some weekly bandwidth to contribute to the repo, so if there is anything you'd like contributions on, let me know.

**Comment by abchapman93** [comment]
Thanks @MichalMalyska ! If you'd like to make a branch off of develop (which now has all the spacy 3 changes) and give this a shot, that would be great! I was planning on doing something like `targets = getattr(doc, "my_custom_spans")` here, but if you have any other ideas for how to do it that would be great too.
