### ISSUE TITLE
Allow QuickUMLS to emit concepts for overlapping text sections via SpanGroup?

### ISSUE THREAD

**Issue by burgersmoke** [medspacy/medspacy#97]
With spacy 3.1, overlapping sections of text can now be handled.  This is a common issue with clinical concepts where they may overlap and with spacy `Entity` we choose only 1 based on scores or length since `Entity` does not allow overlap.

Spacy 3.1 now supports `SpanCategorizer` and `SpanGroup` which might be a preferable data structure since it allows overlapping text spans and also probabilities.  We may want to change QuickUMLS to emit `SpanGroup` either in addition to or instead of `Entity`:

https://spacy.io/api/spancategorizer

**Comment by RonWilkinson** [comment]
I would find the ability to use overlapping spans in MedSpacy to be very useful.  With regards to QuickUMLS, should this be implemented in medspacy_quickumls or in QuickUMLS itself, which has its own developer?

**Comment by burgersmoke** [comment]
This is now supported in medspacy 1.0.0 and unit tests show this.
